website/auth.py
from flask import Blueprint, request, render_template, url_for, redirect
from flask_login import login_user, login_required, logout_user

from .models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        result = User.check_login(email, password)
        if result:
            login_user(result, remember=True)
            return redirect(url_for('views.home'))
        else:
            return render_template('login.html', error=True)

    return render_template('login.html')


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        result = User.validate_email(email)
        if result:
            User.create_new_user(email, password)
            return redirect(url_for('auth.login'))
        else:
            return render_template('register.html', error=True)
    return render_template('register.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from .get_data import *

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    user = current_user
    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')

    tracklist = get_playlist_of_the_day()
    return render_template('playlist_of_the_day.html', user=user, tracklist=tracklist)


@views.route('/search', methods=['GET', 'POST'])
def search():
    user = current_user
    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')
    
    query = request.args['query']
    tracklist = get_tracks(query)
    return render_template('playlist_of_the_day.html', user=user, tracklist=tracklist)


@views.route('/random', methods=['GET'])
def random():
    user = current_user

    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')

    track = get_random_track()
    if user.is_authenticated:
        is_fav = f'{is_favourite(track.isrc, user.user_id)}'.lower()
    else:
        is_fav = 'false'
    return redirect(url_for('views.track_info') + f'?isrc={track.isrc}&favourite={is_fav}')


@views.route('/track', methods=['GET', 'POST'])
def track_info():
    user = current_user

    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')

    isrc = request.args['isrc']
    track = get_track_info(isrc)
    tracklist = get_random_tracklist()
    fav = request.args.get('favourite')
    if user.is_authenticated:
        tracklist = get_similar(track, user.user_id)

        is_fav = f'{is_favourite(isrc, user.user_id)}'.lower()

        add_to_history(isrc, user.user_id)

        if fav is None:
            fav = is_fav

        if is_fav == fav:
            return render_template('track.html', user=user, track=track, is_fav=fav, tracklist=tracklist)
        else:
            if fav == 'true':
                add_to_favourites(isrc, user.user_id)
            else:
                remove_from_favourites(isrc, user.user_id)

            return render_template('track.html', user=user, track=track, is_fav=fav, tracklist=tracklist)
    else:
        if fav is None or fav == "false":
            return render_template('track.html', user=user, track=track, is_fav='false', tracklist=tracklist)
        else:
            return redirect(url_for('auth.login'))


@views.route('/artist', methods=['GET', 'POST'])
def artist_info():
    user = current_user

    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')
    
    artist_id = request.args['id']
    artist = get_artist_info(artist_id)
    tracklist = get_artist_tracks(artist)

    sub = request.args.get('subscribed')

    if user.is_authenticated:
        is_sub = f'{is_subscribed(artist_id, user.user_id)}'.lower()

        if sub is None:
            sub = is_sub

        if is_sub == sub:
            return render_template('artist.html', user=user, artist=artist, is_sub=sub, tracklist=tracklist)
        else:
            if sub == 'true':
                subscribe(artist_id, user.user_id)
            else:
                unsubscribe(artist_id, user.user_id)

            return render_template('artist.html', user=user, artist=artist, is_sub=sub, tracklist=tracklist)
    else:
        if sub is None or sub == "false":
            return render_template('artist.html', user=user, artist=artist, is_sub='false', tracklist=tracklist)
        else:
            return redirect(url_for('auth.login'))


@views.route('/favourites', methods=['GET', 'POST'])
@login_required
def favourites():
    user = current_user

    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')

    tracklist = get_favourites(user.user_id)
    return render_template('favourites.html', user=user, tracklist=tracklist)


@views.route('/stats', methods=['GET', 'POST'])
@login_required
def stats():
    user = current_user

    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')

    genres_plot, artists_plot = get_stats(user.user_id)
    return render_template('stats.html', user=user, genres_plot=genres_plot, artists_plot=artists_plot)


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = current_user

    if request.method == 'POST':
        query = request.form['query']
        return redirect(url_for('views.search') + f'?query={query}')

    tracklist = get_history(user.user_id)
    subscriptions = get_subscriptions(user.user_id)

    return render_template('user.html', user=user, tracklist=tracklist, subscriptions=subscriptions)

website/templates/artist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Artist</title>
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700;900&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <form method="post" class="nav">
        <div class="navigation-left">
            <a href="{{url_for('views.home')}}" class="navigation-link" style="color: black; background-color: white">Playlist of the Day</a>
            <a href="{{url_for('views.random')}}" class="navigation-link">Random</a>
        </div>
        <label class="navigation-searchbar">
            <input  name="query" type="search" class="searchbar" id="searchbar">
            <button name="search" class="search-button" type="submit" id="search">
                <img src="../static/searchicon.png" height="16" , width="16" alt="<">
            </button>
        </label>
        <div class="navigation-right">
            <a href="{{url_for('views.favourites')}}" class="navigation-link">Favourites</a>
            <a href="{{url_for('views.stats')}}" class="navigation-link">Stats</a>
            {% if user.is_authenticated %}
            <a href="{{url_for('views.profile')}}" class="navigation-link">Account</a>
            {% else %}
            <a href="{{url_for('views.profile')}}" class="navigation-link">Join free!</a>
            {% endif %}}
        </div>
    </form>
</header>
<main>
    <div class="artist-wrapper">
        <div class="artist-content">
            <img src="{{artist.image}}" alt="Image Not Found :(" class="artist-image">
            <div class="artist-info">
                <p class="artist-name">{{artist.name}}</p>
                {% if is_sub == 'true' %}
                <a href="{{url_for('views.artist_info')}}?id={{artist.artist_id}}&subscribed=false" class="artist-subscribe" style="background-color: transparent">UNSUBSCRIBE</a>
                {% else %}
                <a href="{{url_for('views.artist_info')}}?id={{artist.artist_id}}&subscribed=true" class="artist-subscribe">SUBSCRIBE</a>
                {% endif%}
            </div>

        </div>
        <p style="color: black; justify-self: center; align-self: center"> Tracks of this artist:</p>
        <div class="track-list" style="height: 99%; align-self: center; justify-self: center">
            {% for track in tracklist %}
            <div class="track">
                <img src="{{track.image}}" class="track-image">
                <div class="track-middle">
                    <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}" class="track-name">{{track.name}}</a>
                    <a href="{{url_for('views.artist_info')}}?id={{track.artist_id}}" class="track-artist">{{track.artist_name}}</a>
                    {% if track.lyrics != "None" %}
                        <a href="{{track.lyrics}}" class="track-lyrics">Lyrics</a>
                    {% endif %}
                </div>
                <div class="track-links">
                    <a href="{{track.spotify_url}}" class="track-link">
                        <img src="../static/spotify.png" height="16" , width="16" alt=" ">&nbsp;Spotify
                    </a>
                    <a href="{{track.itunes_url}}" class="track-link">
                        <img src="../static/itunes.png" height="16" , width="16" alt=" ">&nbsp;iTunes
                    </a>
                    <a href="{{track.yt_url}}" class="track-link">
                        <img src="../static/youtube.png" height="16" , width="16" alt=" ">&nbsp;YT Music
                    </a>
                    <a href="{{track.deezer_url}}" class="track-link">
                        <img src="../static/deezer.png" height="16" , width="16" alt=" ">&nbsp;Deezer
                    </a>

                </div>

            </div>
            {% endfor %}
        </div>
    </div>
</main>
</body>
<script>
    document.getElementById("searchbar").addEventListener("keypress", function onEvent(event) {
        if (event.key === "Enter") {
            document.getElementById("search").click();
        }
    });
    document.getElementById("search").addEventListener("click", function onEvent() {
        console.log(document.getElementById("searchbar").value)
    });
</script>
</html>

website/templates/favourites.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favourites</title>
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <form method="post" class="nav">
            <div class="navigation-left">
                <a href="{{url_for('views.home')}}" class="navigation-link" style="color: black; background-color: white">Playlist of the Day</a>
                <a href="{{url_for('views.random')}}" class="navigation-link">Random</a>
            </div>
            <label class="navigation-searchbar">
                <input  name="query" type="search" class="searchbar" id="searchbar">
                <button name="search" class="search-button" type="submit" id="search">
                    <img src="../static/searchicon.png" height="16" , width="16" alt="<">
                </button>
            </label>
            <div class="navigation-right">
                <a href="{{url_for('views.favourites')}}" class="navigation-link">Favourites</a>
                <a href="{{url_for('views.stats')}}" class="navigation-link">Stats</a>
                {% if user.is_authenticated %}
                <a href="{{url_for('views.profile')}}" class="navigation-link">Account</a>
                {% else %}
                <a href="{{url_for('views.profile')}}" class="navigation-link">Join free!</a>
                {% endif %}}
            </div>
        </form>
    </header>
    <main style="flex-direction: column; align-items: center">
        <h1 style="height: 5%">Favourites</h1>
        <div class="track-list">
            {% for track in tracklist %}
            <div class="track">
                <img src="{{track.image}}" class="track-image">
                <div class="track-middle">
                    <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}" class="track-name">{{track.name}}</a>
                    <a href="{{url_for('views.artist_info')}}?id={{track.artist_id}}" class="track-artist">{{track.artist_name}}</a>
                    {% if track.lyrics != "None" %}
                            <a href="{{track.lyrics}}" class="track-lyrics">Lyrics</a>
                    {% endif %}
                </div>
                <div class="track-links">
                    <a href="{{track.spotify_url}}" class="track-link">
                        <img src="../static/spotify.png" height="16" , width="16" alt=" ">&nbsp;Spotify
                    </a>
                    <a href="{{track.itunes_url}}" class="track-link">
                        <img src="../static/itunes.png" height="16" , width="16" alt=" ">&nbsp;iTunes
                    </a>
                    <a href="{{track.yt_url}}" class="track-link">
                        <img src="../static/youtube.png" height="16" , width="16" alt=" ">&nbsp;YT Music
                    </a>
                    <a href="{{track.deezer_url}}" class="track-link">
                        <img src="../static/deezer.png" height="16" , width="16" alt=" ">&nbsp;Deezer
                    </a>

                </div>

            </div>
            {% endfor %}
        </div>
    </main>
</body>
<script>
    document.getElementById("searchbar").addEventListener("keypress", function onEvent(event) {
        if (event.key === "Enter") {
            document.getElementById("search").click();
        }
    });
    document.getElementById("search").addEventListener("click", function onEvent() {
        console.log(document.getElementById("searchbar").value)
    });
</script>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign In</title>
    <link href="../static/styles.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <form class="auth-wrapper" method="post">
        <div class="auth-content">
            <h1 class="auth-label">Nice to see you again!</h1>

            <div class="auth-inputs">
                <label class="auth-input-label">
                    E-mail: <input type="text" placeholder="Email" name="email" id="login" class="auth-input">
                </label>
                <label class="auth-input-label">
                    Password:<input type="password" placeholder="Password" name="password" id="password" class="auth-input">
                </label>
            </div>

            <input type="submit" class="auth-button" value="SIGN IN">

            <a href="{{url_for('auth.register')}}" class="auth-button" style="background-color: white ;color: black; border-color: white">NEW USER?</a>
        </div>
        {% if error %}
        <p id="error" style="width: 50%; text-align: center; font-size: 16px; background-color: white;color: black; padding: 15px; border-radius: 2em">Invalid email or password</p>
        {% endif %}
        <a href="{{url_for('views.home')}}" style="color: black">To main page</a>
    </form>
</body>
<script>
</script>
</html>

website/templates/playlist_of_the_day.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Playlist of the Day</title>
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <form method="post" class="nav">
            <div class="navigation-left">
                <a href="{{url_for('views.home')}}" class="navigation-link" style="color: black; background-color: white">Playlist of the Day</a>
                <a href="{{url_for('views.random')}}" class="navigation-link">Random</a>
            </div>
            <label class="navigation-searchbar">
                <input  name="query" type="search" class="searchbar" id="searchbar">
                <button name="search" class="search-button" type="submit" id="search">
                    <img src="../static/searchicon.png" height="16" , width="16" alt="<">
                </button>
            </label>
            <div class="navigation-right">
                <a href="{{url_for('views.favourites')}}" class="navigation-link">Favourites</a>
                <a href="{{url_for('views.stats')}}" class="navigation-link">Stats</a>
                {% if user.is_authenticated %}
                <a href="{{url_for('views.profile')}}" class="navigation-link">Account</a>
                {% else %}
                <a href="{{url_for('views.profile')}}" class="navigation-link">Join free!</a>
                {% endif %}}
            </div>
        </form>
    </header>
    <main>
        <div>
            <div class="track-list">
                {% for track in tracklist %}
                <div class="track">
                    <img src="{{track.image}}" class="track-image">
                    <div class="track-middle">
                        <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}" class="track-name">{{track.name}}</a>
                        <a href="{{url_for('views.artist_info')}}?id={{track.artist_id}}" class="track-artist">{{track.artist_name}}</a>
                        {% if track.lyrics != "None" %}
                            <a href="{{track.lyrics}}" class="track-lyrics">Lyrics</a>
                        {% endif %}
                    </div>
                    <div class="track-links">
                        <a href="{{track.spotify_url}}" class="track-link">
                            <img src="../static/spotify.png" height="16" , width="16" alt=" ">&nbsp;Spotify
                        </a>
                        <a href="{{track.itunes_url}}" class="track-link">
                            <img src="../static/itunes.png" height="16" , width="16" alt=" ">&nbsp;iTunes
                        </a>
                        <a href="{{track.yt_url}}" class="track-link">
                            <img src="../static/youtube.png" height="16" , width="16" alt=" ">&nbsp;YT Music
                        </a>
                        <a href="{{track.deezer_url}}" class="track-link">
                            <img src="../static/deezer.png" height="16" , width="16" alt=" ">&nbsp;Deezer
                        </a>

                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </main>
</body>
<script>
    document.getElementById("searchbar").addEventListener("keypress", function onEvent(event) {
        if (event.key === "Enter") {
            document.getElementById("search").click();
        }
    });
    document.getElementById("search").addEventListener("click", function onEvent() {

    });
</script>
</html>

website/templates/track.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Track</title>
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <form method="post" class="nav">
            <div class="navigation-left">
                <a href="{{url_for('views.home')}}" class="navigation-link" style="color: black; background-color: white">Playlist of the Day</a>
                <a href="{{url_for('views.random')}}" class="navigation-link">Random</a>
            </div>
            <label class="navigation-searchbar">
                <input  name="query" type="search" class="searchbar" id="searchbar">
                <button name="search" class="search-button" type="submit" id="search">
                    <img src="../static/searchicon.png" height="16" , width="16" alt="<">
                </button>
            </label>
            <div class="navigation-right">
                <a href="{{url_for('views.favourites')}}" class="navigation-link">Favourites</a>
                <a href="{{url_for('views.stats')}}" class="navigation-link">Stats</a>
                {% if user.is_authenticated %}
                <a href="{{url_for('views.profile')}}" class="navigation-link">Account</a>
                {% else %}
                <a href="{{url_for('views.profile')}}" class="navigation-link">Join free!</a>
                {% endif %}}
            </div>
        </form>
    </header>
    <main>
        <div class="track-wrapper">
            <div class="track-info">
                <img src="{{track.image}}" alt="Image Not Found :(" class="track-image">
                <div class="track-middle">
                    <form method="post" style="display:flex; width: 100%; grid-area: a;flex-direction: row">
                        <p class="track-name">{{track.name}}</p>
                        {% if is_fav == 'true' %}
                        <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}&favourite=false" name="dislike" id="like_button" class="track-like" style="background-image: url('../static/like.png')"></a>
                        {% else %}
                        <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}&favourite=true" name="dislike" id="like_button" class="track-like" style="background-image: url('../static/not like.png')"></a>
                        {% endif%}
                    </form>
                    <a href="{{url_for('views.artist_info')}}?id={{track.artist_id}}" class="track-artist">{{track.artist_name}}</a>
                    {% if track.lyrics != "None" %}
                        <a href="{{track.lyrics}}" class="track-lyrics">Lyrics</a>
                    {% endif %}
                </div>
                <div class="track-links">
                    <a href="{{track.spotify_url}}" class="track-link">
                        <img src="../static/spotify.png" height="32" , width="32" alt=" ">&nbsp;Spotify
                    </a>
                    <a href="{{track.itunes_url}}" class="track-link">
                        <img src="../static/itunes.png" height="32" , width="32" alt=" ">&nbsp;iTunes
                    </a>
                    <a href="{{track.yt_url}}" class="track-link">
                        <img src="../static/youtube.png" height="32" , width="32" alt=" ">&nbsp;YT Music
                    </a>
                    <a href="{{track.deezer_url}}" class="track-link">
                        <img src="../static/deezer.png" height="32" , width="32" alt=" ">&nbsp;Deezer
                    </a>

                </div>
            </div>
            <p style="color: black; justify-self: center; align-self: center"> Similar tracks:</p>
            <div class="track-list" style="height: 99%; align-self: center; justify-self: center">
                {% for track in tracklist %}
                <div class="track">
                    <img src="{{track.image}}" class="track-image">
                    <div class="track-middle">
                        <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}" class="track-name">{{track.name}}</a>
                        <a href="{{url_for('views.artist_info')}}?id={{track.artist_id}}" class="track-artist">{{track.artist_name}}</a>
                        {% if track.lyrics != "None" %}
                            <a href="{{track.lyrics}}" class="track-lyrics">Lyrics</a>
                        {% endif %}
                    </div>
                    <div class="track-links">
                        <a href="{{track.spotify_url}}" class="track-link">
                            <img src="../static/spotify.png" height="16" , width="16" alt=" ">&nbsp;Spotify
                        </a>
                        <a href="{{track.yt_url}}" class="track-link">
                            <img src="../static/itunes.png" height="16" , width="16" alt=" ">&nbsp;iTunes
                        </a>
                        <a href="{{track.itunes_url}}" class="track-link">
                            <img src="../static/youtube.png" height="16" , width="16" alt=" ">&nbsp;YT Music
                        </a>
                        <a href="{{track.deezer_url}}" class="track-link">
                            <img src="../static/deezer.png" height="16" , width="16" alt=" ">&nbsp;Deezer
                        </a>

                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </main>
</body>
<script>
    document.getElementById("searchbar").addEventListener("keypress", function onEvent(event) {
        if (event.key === "Enter") {
            document.getElementById("search").click();
        }
    });
    document.getElementById("search").addEventListener("click", function onEvent() {
        console.log(document.getElementById("searchbar").value)
    });
</script>
</html>

website/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User cabinet</title>
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <form method="post" class="nav">
            <div class="navigation-left">
                <a href="{{url_for('views.home')}}" class="navigation-link" style="color: black; background-color: white">Playlist of the Day</a>
                <a href="{{url_for('views.random')}}" class="navigation-link">Random</a>
            </div>
            <label class="navigation-searchbar">
                <input  name="query" type="search" class="searchbar" id="searchbar">
                <button name="search" class="search-button" type="submit" id="search">
                    <img src="../static/searchicon.png" height="16" , width="16" alt="<">
                </button>
            </label>
            <div class="navigation-right">
                <a href="{{url_for('views.favourites')}}" class="navigation-link">Favourites</a>
                <a href="{{url_for('views.stats')}}" class="navigation-link">Stats</a>
                <a href="{{url_for('auth.logout')}}" class="navigation-link">Log Out</a>
            </div>
        </form>
    </header>
    <main>
        <div class="user-wrapper">
            <div class="user-subscriptions">
                <h1 style="color: black; height: 5%">Subscriptions</h1>
                <div class="user-artist-list">
                    {% for subscription in subscriptions %}
                    <a href="{{url_for('views.artist_info')}}?id={{subscription.artist_id}}" class="user-subscription">
                        <img src="{{subscription.image}}" alt="Image Not Found :(" class="user-artist">
                        <p style="color: black; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                            {{subscription.name}}</p>
                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="user-content">
                <div class="user-name" style="justify-content: space-around">
                    <h1 style="font-size: 36px; color: black">{{user.email}}</h1>
                    <h1 style="color: black">History</h1>
                </div>

                <div class="track-list" style="grid-area: b; width: 90%; height: 100%; justify-self: center">
                    {% for track in tracklist %}
                    <div class="track">
                        <img src="{{track.image}}" class="track-image">
                        <div class="track-middle">
                            <a href="{{url_for('views.track_info')}}?isrc={{track.isrc}}" class="track-name">{{track.name}}</a>
                            <a href="{{url_for('views.artist_info')}}?id={{track.artist_id}}" class="track-artist">{{track.artist_name}}</a>
                            {% if track.lyrics != "None" %}
                                <a href="{{track.lyrics}}" class="track-lyrics">Lyrics</a>
                            {% endif %}
                        </div>
                        <div class="track-links">
                            <a href="{{track.spotify_url}}" class="track-link">
                                <img src="../static/spotify.png" height="16" , width="16" alt=" ">&nbsp;Spotify
                            </a>
                            <a href="{{track.itunes_url}}" class="track-link">
                                <img src="../static/itunes.png" height="16" , width="16" alt=" ">&nbsp;iTunes
                            </a>
                            <a href="{{track.yt_url}}" class="track-link">
                                <img src="../static/youtube.png" height="16" , width="16" alt=" ">&nbsp;YT Music
                            </a>
                            <a href="{{track.deezer_url}}" class="track-link">
                                <img src="../static/deezer.png" height="16" , width="16" alt=" ">&nbsp;Deezer
                            </a>

                        </div>

                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
</body>
<script>
    document.getElementById("searchbar").addEventListener("keypress", function onEvent(event) {
        if (event.key === "Enter") {
            document.getElementById("search").click();
        }
    });
    document.getElementById("search").addEventListener("click", function onEvent() {
        console.log(document.getElementById("searchbar").value)
    });
</script>
</html>